name: blacklist
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.22.0
  page_transition: ^2.0.4
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.3
  firebase_auth: ^4.14.1
  intl: ^0.17.0
  firebase_app_check: ^0.2.1+6
  firebase_storage: ^11.5.3
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  image_picker_web: any
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/LogoSinFondo.svg
