// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX10vRDohhACAxKgyS_eECO7wPwUYe0c4',
    appId: '1:707318873674:web:111b361b2ce1c2bcd9f0b3',
    messagingSenderId: '707318873674',
    projectId: 'fraudfighter-2023',
    authDomain: 'fraudfighter-2023.firebaseapp.com',
    storageBucket: 'fraudfighter-2023.appspot.com',
    measurementId: 'G-0T1ZF2YV4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3oI848QkwFGeB_6tQaocEyB_mpSdINAY',
    appId: '1:707318873674:android:fefdcac3669b04e9d9f0b3',
    messagingSenderId: '707318873674',
    projectId: 'fraudfighter-2023',
    storageBucket: 'fraudfighter-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz5_6hHCu3a48ejylqNdIj2wshCYCjdOE',
    appId: '1:707318873674:ios:a5a995ff5ccf9c15d9f0b3',
    messagingSenderId: '707318873674',
    projectId: 'fraudfighter-2023',
    storageBucket: 'fraudfighter-2023.appspot.com',
    iosBundleId: 'com.example.blacklist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz5_6hHCu3a48ejylqNdIj2wshCYCjdOE',
    appId: '1:707318873674:ios:e7099fb11472ef63d9f0b3',
    messagingSenderId: '707318873674',
    projectId: 'fraudfighter-2023',
    storageBucket: 'fraudfighter-2023.appspot.com',
    iosBundleId: 'com.example.blacklist.RunnerTests',
  );
}
